export const usersMock = [
  {
    id: 1,
    email: "john.doe@example.com",
    role: "PATIENT",
    firstName: "John",
    lastName: "Doe",
    isActive: true,
    createdAt: "2024-03-10",
  },
  {
    id: 2,
    email: "mary.smith@example.com",
    role: "DOCTOR",
    firstName: "Mary",
    lastName: "Smith",
    isActive: true,
    createdAt: "2024-02-22",
  },
  {
    id: 3,
    email: "ivan.petrov@example.com",
    role: "GUARDIAN",
    firstName: "Ivan",
    lastName: "Petrov",
    isActive: false,
    createdAt: "2024-01-15",
  },
  {
    id: 4,
    email: "elena.georgieva@example.com",
    role: "PATIENT",
    firstName: "Elena",
    lastName: "Georgieva",
    isActive: true,
    createdAt: "2024-04-01",
  },
  {
    id: 5,
    email: "dr.ivanov@example.com",
    role: "DOCTOR",
    firstName: "Georgi",
    lastName: "Ivanov",
    isActive: true,
    createdAt: "2024-03-18",
  },
  {
    id: 6,
    email: "petar.nikolov@example.com",
    role: "PATIENT",
    firstName: "Petar",
    lastName: "Nikolov",
    isActive: false,
    createdAt: "2023-12-05",
  },
  {
    id: 7,
    email: "maria.dimitrova@example.com",
    role: "GUARDIAN",
    firstName: "Maria",
    lastName: "Dimitrova",
    isActive: true,
    createdAt: "2024-02-10",
  },
  {
    id: 8,
    email: "dr.stoyanov@example.com",
    role: "DOCTOR",
    firstName: "Stoyan",
    lastName: "Stoyanov",
    isActive: false,
    createdAt: "2023-11-28",
  },
  {
    id: 9,
    email: "kalina.popova@example.com",
    role: "PATIENT",
    firstName: "Kalina",
    lastName: "Popova",
    isActive: true,
    createdAt: "2024-04-12",
  },
  {
    id: 10,
    email: "admin.test@example.com",
    role: "PATIENT",
    firstName: "Test",
    lastName: "User",
    isActive: true,
    createdAt: "2024-05-01",
  },
];
